### ISSUE TITLE
Question on MySQL 8.x

### ISSUE THREAD

**Issue by dublx** [fastify/fastify-mysql#24] opened 2019-06-05 15:04 UTC
Hi,

At the start of the README it's stated:

```
Disclaimer: MySQL 8.x databases are not compatible ! This plugin is compatible with MySQL 5.5.x, MySQL 5.7.x and MariaDB databases.
```

I have been using it to connect to a MySQL 8.x installation without any issues.
So what is the reason for the disclaimer?
ps: im using `"fastify-mysql": "^0.2.0"`

Thanks!

**Comment by Eomm** [comment] 2019-06-05 20:01
I can't find right now the correct issue I looked at, but the cause of the disclaimer is that this lib:
https://github.com/sidorares/node-mysql2

doesn't support totally that version of MySQL (maybe not some feature):
https://github.com/sidorares/node-mysql2/blob/master/.travis.yml

I can find the right issue but feel free to give it a check

**Comment by dublx** [comment] 2019-06-06 10:59
Thanks!

**Comment by mcollina** [comment] 2019-06-08 15:24
I’d be happy to support all versions of mysql and mariadb if we can use another client.

**Comment by sidorares** [comment] 2019-10-21 02:46
Mysql8 default auth is supported in `mysql2@2.0-alpha1`, I'm planning to publish alpha1 as a release today

**Comment by sidorares** [comment] 2019-10-27 07:59
mysql2@2.0.0 is out

**Comment by mcollina** [comment] 2019-10-27 08:37
Thanks

**Comment by mcollina** [comment] 2019-10-27 08:38
@dublx would you like to send a PR?

**Comment by Eomm** [comment] 2019-10-31 21:48
Relesed in v1.0.0 official support to MySQL8

https://github.com/fastify/fastify-mysql/releases/tag/v1.0.0

Closing

**Closed by Eomm** 2019-10-31 21:48 UTC
